"""empty message

Revision ID: 5e430825deff
Revises: 4dbe07546f96
Create Date: 2022-11-03 18:11:52.396389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e430825deff'
down_revision = '4dbe07546f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('express', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'express')
    # ### end Alembic commands ###
